"""Начальное заполнение биографических полей персоналий (одноразовый скрипт, сентябрь–октябрь 2026).

Данные внесены по общим справочным сведениям, НЕ из книги Уилсона; у всех карточек bio_checked: false.
Повторный запуск не перезаписывает уже существующие поля.
"""
L = lambda *ids: [f"[[{i}]]" for i in ids]
LON, CAM, OXF, PAR, VIE, NYC, EDI, BER = [51.5074, -0.1278], [52.2053, 0.1218], [51.7520, -1.2577], [48.8566, 2.3522], [48.2082, 16.3738], [40.7128, -74.0060], [55.9533, -3.1883], [52.5200, 13.4050]
BIO = {
 "alfred-north-whitehead": dict(born="1861-02-15", birth_place="Рамсгит, Англия", birth_coords=[51.335, 1.419], died="1947-12-30", death_place="Кембридж, Массачусетс, США", death_coords=[42.3736, -71.1097], nationality="британец", alma_mater="Тринити-колледж, Кембридж", affiliations=["Тринити-колледж, Кембридж", "Имперский колледж, Лондон", "Гарвардский университет"], fields=["математика", "логика", "философия процесса"], students=L("bertrand-russell", "willard-quine"), sep="https://plato.stanford.edu/entries/whitehead/"),
 "alfred-tennison": dict(born="1809-08-06", birth_place="Сомерсби, Линкольншир, Англия", birth_coords=[53.25, 0.01], died="1892-10-06", death_place="Олдуорт близ Хейзлмира, Англия", death_coords=[51.08, -0.72], nationality="британец", alma_mater="Тринити-колледж, Кембридж", fields=["поэзия"], awards=["Поэт-лауреат Великобритании (1850)"]),
 "anthony-of-padua": dict(born="1195", birth_place="Лиссабон, Португалия", birth_coords=[38.7223, -9.1393], died="1231-06-13", death_place="Арчелла близ Падуи, Италия", death_coords=[45.4064, 11.8768], nationality="португалец", affiliations=["Орден францисканцев"], fields=["богословие", "проповедь"]),
 "bernard-bosanquet": dict(born="1848-06-14", birth_place="Рок-Холл близ Алника, Нортумберленд, Англия", birth_coords=[55.45, -1.70], died="1923-02-08", death_place="Лондон", death_coords=LON, nationality="британец", alma_mater="Баллиол-колледж, Оксфорд", affiliations=["Университетский колледж, Оксфорд", "Сент-Эндрюсский университет"], fields=["абсолютный идеализм", "эстетика", "логика"]),
 "bertrand-russell": dict(born="1872-05-18", birth_place="Треллек, Уэльс", birth_coords=[51.75, -2.78], died="1970-02-02", death_place="Пенриндейдрайт, Уэльс", death_coords=[52.93, -4.07], nationality="британец", alma_mater="Тринити-колледж, Кембридж", affiliations=["Тринити-колледж, Кембридж", "Чикагский университет", "Калифорнийский университет в Лос-Анджелесе"], fields=["математическая логика", "аналитическая философия", "эпистемология"], teachers=L("alfred-north-whitehead"), students=L("ludwig-wittgenstein"), colleagues=L("gottlob-frege", "godfri-kharold-khardi"), awards=["Нобелевская премия по литературе (1950)"], sep="https://plato.stanford.edu/entries/russell/"),
 "buster-keaton": dict(born="1895-10-04", birth_place="Пикуа, Канзас, США", birth_coords=[37.92, -95.53], died="1966-02-01", death_place="Вудленд-Хиллз, Лос-Анджелес, США", death_coords=[34.168, -118.605], nationality="американец", fields=["кино", "комедия"], awards=["Почётный «Оскар» (1960)"]),
 "cary-grant": dict(born="1904-01-18", birth_place="Бристоль, Англия", birth_coords=[51.4545, -2.5879], died="1986-11-29", death_place="Дэвенпорт, Айова, США", death_coords=[41.5236, -90.5776], nationality="британец, американец", fields=["кино"], awards=["Почётный «Оскар» (1970)"]),
 "charles-darwin": dict(born="1809-02-12", birth_place="Шрусбери, Англия", birth_coords=[52.7073, -2.7553], died="1882-04-19", death_place="Даун-Хаус, Даун, Кент, Англия", death_coords=[51.33, 0.05], nationality="британец", alma_mater="Эдинбургский университет; Крайст-колледж, Кембридж", fields=["естествознание", "эволюционная биология", "геология"], colleagues=L("t-h-huxley"), awards=["Медаль Копли (1864)"]),
 "charles-lamb": dict(born="1775-02-10", birth_place="Лондон", birth_coords=LON, died="1834-12-27", death_place="Эдмонтон, Лондон", death_coords=[51.62, -0.06], nationality="британец", alma_mater="школа Христова госпиталя, Лондон", fields=["эссеистика", "литературная критика"], colleagues=L("coleridge", "william-hazlitt", "william-wordsworth", "r-southey")),
 "coleridge": dict(born="1772-10-21", birth_place="Оттери-Сент-Мэри, Девон, Англия", birth_coords=[50.75, -3.28], died="1834-07-25", death_place="Хайгейт, Лондон", death_coords=[51.57, -0.15], nationality="британец", alma_mater="Джизус-колледж, Кембридж", fields=["поэзия", "литературная критика", "философия"], colleagues=L("william-wordsworth", "r-southey", "charles-lamb", "william-hazlitt")),
 "crispin-wright": dict(born="1942", nationality="британец", alma_mater="Тринити-колледж, Кембридж; Оксфордский университет", affiliations=["Сент-Эндрюсский университет", "Нью-Йоркский университет", "Университет Стерлинга"], fields=["философия языка", "философия математики", "эпистемология"], colleagues=L("michael-dummett")),
 "david-hume": dict(born="1711-05-07", birth_place="Эдинбург, Шотландия", birth_coords=EDI, died="1776-08-25", death_place="Эдинбург, Шотландия", death_coords=EDI, nationality="шотландец", alma_mater="Эдинбургский университет", fields=["эмпиризм", "скептицизм", "этика", "история"], sep="https://plato.stanford.edu/entries/hume/"),
 "david-lewis": dict(born="1941-09-28", birth_place="Оберлин, Огайо, США", birth_coords=[41.2939, -82.2174], died="2001-10-14", death_place="Принстон, Нью-Джерси, США", death_coords=[40.3573, -74.6672], nationality="американец", alma_mater="Суортмор-колледж; Гарвардский университет", affiliations=["Калифорнийский университет в Лос-Анджелесе", "Принстонский университет"], fields=["метафизика", "философия языка", "модальная логика"], teachers=L("willard-quine"), students=L("robert-brandom"), sep="https://plato.stanford.edu/entries/david-lewis/"),
 "david-whisnant": dict(born="1938", died="2024", nationality="американец", affiliations=["Университет Северной Каролины в Чапел-Хилле"], fields=["американистика", "фольклористика", "культурная политика"]),
 "doctor-seuss": dict(born="1904-03-02", birth_place="Спрингфилд, Массачусетс, США", birth_coords=[42.1015, -72.5898], died="1991-09-24", death_place="Ла-Холья, Калифорния, США", death_coords=[32.8328, -117.2713], nationality="американец", alma_mater="Дартмутский колледж; Линкольн-колледж, Оксфорд", fields=["детская литература", "иллюстрация"], awards=["Специальная Пулитцеровская премия (1984)"]),
 "duke-of-iron": dict(born="1906", died="1968", nationality="тринидадец", fields=["калипсо"]),
 "dzherri-fodor": dict(born="1935-04-22", birth_place="Нью-Йорк, США", birth_coords=NYC, died="2017-11-29", death_place="Нью-Йорк, США", death_coords=NYC, nationality="американец", alma_mater="Колумбийский колледж; Принстонский университет", affiliations=["Массачусетский технологический институт", "Ратгерский университет"], fields=["философия сознания", "когнитивная наука"], teachers=L("hilary-putnam")),
 "edward-lippmann": dict(born="1920", died="2010", nationality="американец", affiliations=["Колумбийский университет"], fields=["музыковедение", "музыкальная эстетика"]),
 "ernst-mach": dict(born="1838-02-18", birth_place="Хирлиц (Хрлице) близ Брюнна, Моравия", birth_coords=[49.13, 16.65], died="1916-02-19", death_place="Фатерштеттен близ Мюнхена, Германия", death_coords=[48.105, 11.769], nationality="австриец", alma_mater="Венский университет", affiliations=["Грацский университет", "Пражский (Карлов) университет", "Венский университет"], fields=["физика", "психофизика", "философия науки"], sep="https://plato.stanford.edu/entries/ernst-mach/"),
 "f-t-vischer": dict(born="1807-06-30", birth_place="Людвигсбург, Вюртемберг", birth_coords=[48.8975, 9.1919], died="1887-09-14", death_place="Гмунден, Австрия", death_coords=[47.918, 13.799], nationality="немец", alma_mater="Тюбингенский университет", affiliations=["Тюбингенский университет", "Цюрихский политехникум"], fields=["эстетика", "литература"]),
 "frank-and-anne-warner": dict(nationality="американцы", fields=["фольклористика", "полевые записи"]),
 "frank-jackson": dict(born="1943-08-31", birth_place="Мельбурн, Австралия", birth_coords=[-37.8136, 144.9631], nationality="австралиец", alma_mater="Мельбурнский университет; Университет Ла Троба", affiliations=["Австралийский национальный университет"], fields=["философия сознания", "метафизика"]),
 "franz-reuleaux": dict(born="1829-09-30", birth_place="Эшвайлер, Пруссия", birth_coords=[50.8172, 6.2650], died="1905-08-20", death_place="Берлин", death_coords=BER, nationality="немец", alma_mater="Политехникум Карлсруэ", affiliations=["Цюрихский политехникум", "Королевская ремесленная академия (Технический университет Берлина)"], fields=["кинематика машин", "машиноведение"]),
 "fritz-winckel": dict(born="1907", died="2000", nationality="немец", affiliations=["Технический университет Берлина"], fields=["акустика", "музыкальная психоакустика"]),
 "george-berkeley": dict(born="1685-03-12", birth_place="Дайсарт близ Томастауна, Килкенни, Ирландия", birth_coords=[52.53, -7.14], died="1753-01-14", death_place="Оксфорд, Англия", death_coords=OXF, nationality="ирландец", alma_mater="Тринити-колледж, Дублин", affiliations=["Тринити-колледж, Дублин", "епископ Клойнский (с 1734)"], fields=["эмпиризм", "идеализм", "теория зрения"], sep="https://plato.stanford.edu/entries/berkeley/"),
 "giuseppe-tartini": dict(born="1692-04-08", birth_place="Пирано, Истрия (Венецианская республика)", birth_coords=[45.528, 13.568], died="1770-02-26", death_place="Падуя", death_coords=[45.4064, 11.8768], nationality="итальянец", alma_mater="Падуанский университет", fields=["скрипка", "композиция", "теория музыки"]),
 "godfri-kharold-khardi": dict(born="1877-02-07", birth_place="Кранли, Суррей, Англия", birth_coords=[51.141, -0.488], died="1947-12-01", death_place="Кембридж, Англия", death_coords=CAM, nationality="британец", alma_mater="Тринити-колледж, Кембридж", affiliations=["Тринити-колледж, Кембридж", "Нью-колледж, Оксфорд"], fields=["теория чисел", "математический анализ"], colleagues=L("bertrand-russell")),
 "gottlob-frege": dict(born="1848-11-08", birth_place="Висмар, Мекленбург", birth_coords=[53.8913, 11.4650], died="1925-07-26", death_place="Бад-Кляйнен, Мекленбург", death_coords=[53.77, 11.47], nationality="немец", alma_mater="Йенский университет; Гёттингенский университет", affiliations=["Йенский университет"], fields=["логика", "философия математики", "философия языка"], colleagues=L("bertrand-russell", "ludwig-wittgenstein"), sep="https://plato.stanford.edu/entries/frege/"),
 "heinrich-hertz": dict(born="1857-02-22", birth_place="Гамбург", birth_coords=[53.5511, 9.9937], died="1894-01-01", death_place="Бонн", death_coords=[50.7374, 7.0982], nationality="немец", alma_mater="Берлинский университет", affiliations=["Кильский университет", "Политехникум Карлсруэ", "Боннский университет"], fields=["физика", "электродинамика", "механика"], teachers=L("hermann-helmholtz")),
 "helen-keller": dict(born="1880-06-27", birth_place="Таскамбия, Алабама, США", birth_coords=[34.7309, -87.7025], died="1968-06-01", death_place="Истон, Коннектикут, США", death_coords=[41.25, -73.30], nationality="американка", alma_mater="Рэдклифф-колледж", fields=["литература", "общественная деятельность"], awards=["Президентская медаль Свободы (1964)"]),
 "hermann-helmholtz": dict(born="1821-08-31", birth_place="Потсдам, Пруссия", birth_coords=[52.3906, 13.0645], died="1894-09-08", death_place="Шарлоттенбург (Берлин)", death_coords=[52.5167, 13.30], nationality="немец", alma_mater="Медико-хирургический институт Фридриха Вильгельма, Берлин", affiliations=["Кёнигсбергский университет", "Боннский университет", "Гейдельбергский университет", "Берлинский университет"], fields=["физиология", "физика", "физиологическая акустика и оптика"], students=L("heinrich-hertz")),
 "hilaire-belloc": dict(born="1870-07-27", birth_place="Ла-Сель-Сен-Клу, Франция", birth_coords=[48.85, 2.13], died="1953-07-16", death_place="Гилфорд, Англия", death_coords=[51.2362, -0.5704], nationality="британец французского происхождения", alma_mater="Баллиол-колледж, Оксфорд", fields=["поэзия", "эссеистика", "история"]),
 "hilary-putnam": dict(born="1926-07-31", birth_place="Чикаго, США", birth_coords=[41.8781, -87.6298], died="2016-03-13", death_place="Арлингтон, Массачусетс, США", death_coords=[42.4154, -71.1565], nationality="американец", alma_mater="Пенсильванский университет; Калифорнийский университет в Лос-Анджелесе", affiliations=["Принстонский университет", "Массачусетский технологический институт", "Гарвардский университет"], fields=["философия языка", "философия сознания", "философия науки"], students=L("dzherri-fodor"), colleagues=L("willard-quine")),
 "immanuel-kant": dict(born="1724-04-22", birth_place="Кёнигсберг, Пруссия", birth_coords=[54.7104, 20.4522], died="1804-02-12", death_place="Кёнигсберг, Пруссия", death_coords=[54.7104, 20.4522], nationality="немец", alma_mater="Кёнигсбергский университет", affiliations=["Кёнигсбергский университет"], fields=["эпистемология", "метафизика", "этика", "эстетика"], sep="https://plato.stanford.edu/entries/kant/"),
 "isaac-hawkins-browne": dict(born="1705-01-21", birth_place="Бертон-апон-Трент, Англия", birth_coords=[52.8019, -1.6370], died="1760-02-14", death_place="Лондон", death_coords=LON, nationality="британец", alma_mater="Тринити-колледж, Кембридж", fields=["поэзия", "пародия"]),
 "isaac-newton": dict(born="1643-01-04", birth_place="Вулсторп, Линкольншир, Англия", birth_coords=[52.809, -0.631], died="1727-03-31", death_place="Кенсингтон, Лондон", death_coords=[51.50, -0.19], nationality="англичанин", alma_mater="Тринити-колледж, Кембридж", affiliations=["Кембриджский университет", "Королевский монетный двор", "Королевское общество (президент с 1703)"], fields=["механика", "оптика", "математический анализ"], sep="https://plato.stanford.edu/entries/newton/", notes="Даты по григорианскому календарю; по юлианскому — 25.12.1642 – 20.03.1726/27."),
 "j-l-austin": dict(born="1911-03-26", birth_place="Ланкастер, Англия", birth_coords=[54.0466, -2.8007], died="1960-02-08", death_place="Оксфорд, Англия", death_coords=OXF, nationality="британец", alma_mater="Баллиол-колледж, Оксфорд", affiliations=["Оксфордский университет"], fields=["философия обыденного языка", "теория речевых актов"], sep="https://plato.stanford.edu/entries/austin-jl/"),
 "jacques-hadamard": dict(born="1865-12-08", birth_place="Версаль, Франция", birth_coords=[48.8049, 2.1204], died="1963-10-17", death_place="Париж", death_coords=PAR, nationality="француз", alma_mater="Высшая нормальная школа", affiliations=["Коллеж де Франс", "Политехническая школа", "Парижский университет"], fields=["математический анализ", "теория чисел", "дифференциальные уравнения"]),
 "james-thomson": dict(born="1700-09-11", birth_place="Эднам, Роксбургшир, Шотландия", birth_coords=[55.62, -2.42], died="1748-08-27", death_place="Ричмонд, Суррей, Англия", death_coords=[51.461, -0.303], nationality="шотландец", alma_mater="Эдинбургский университет", fields=["поэзия"]),
 "jean-piaget": dict(born="1896-08-09", birth_place="Невшатель, Швейцария", birth_coords=[46.99, 6.93], died="1980-09-16", death_place="Женева, Швейцария", death_coords=[46.2044, 6.1432], nationality="швейцарец", alma_mater="Невшательский университет", affiliations=["Женевский университет", "Институт Жан-Жака Руссо"], fields=["психология развития", "генетическая эпистемология"]),
 "jeff-todd-titon": dict(born="1943", nationality="американец", affiliations=["Брауновский университет"], fields=["этномузыкология", "фольклористика"]),
 "john-dewey": dict(born="1859-10-20", birth_place="Берлингтон, Вермонт, США", birth_coords=[44.4759, -73.2121], died="1952-06-01", death_place="Нью-Йорк, США", death_coords=NYC, nationality="американец", alma_mater="Вермонтский университет; Университет Джонса Хопкинса", affiliations=["Чикагский университет", "Колумбийский университет"], fields=["прагматизм", "философия образования", "эпистемология"], sep="https://plato.stanford.edu/entries/dewey/"),
 "joseph-addison": dict(born="1672-05-01", birth_place="Милстон, Уилтшир, Англия", birth_coords=[51.24, -1.77], died="1719-06-17", death_place="Холланд-Хаус, Кенсингтон, Лондон", death_coords=[51.5023, -0.2045], nationality="англичанин", alma_mater="Куинз-колледж и Модлин-колледж, Оксфорд", fields=["эссеистика", "журналистика", "драматургия"]),
 "l-susan-stebbing": dict(born="1885-12-02", birth_place="Уимблдон, Лондон", birth_coords=[51.4214, -0.2064], died="1943-09-11", death_place="Лондон", death_coords=LON, nationality="британка", alma_mater="Гиртон-колледж, Кембридж", affiliations=["Бедфорд-колледж, Лондонский университет"], fields=["логика", "аналитическая философия", "критическое мышление"]),
 "leonhard-euler": dict(born="1707-04-15", birth_place="Базель, Швейцария", birth_coords=[47.5596, 7.5886], died="1783-09-18", death_place="Санкт-Петербург", death_coords=[59.9311, 30.3609], nationality="швейцарец", alma_mater="Базельский университет", affiliations=["Петербургская академия наук", "Берлинская академия наук"], fields=["математика", "механика", "астрономия"]),
 "ludwig-wittgenstein": dict(born="1889-04-26", birth_place="Вена, Австро-Венгрия", birth_coords=VIE, died="1951-04-29", death_place="Кембридж, Англия", death_coords=CAM, nationality="австриец, британский подданный с 1939", alma_mater="Высшая техническая школа Шарлоттенбурга; Манчестерский университет; Тринити-колледж, Кембридж", affiliations=["Тринити-колледж, Кембридж"], fields=["философия языка", "философия логики", "философия математики"], teachers=L("bertrand-russell"), colleagues=L("gottlob-frege"), sep="https://plato.stanford.edu/entries/wittgenstein/"),
 "m-h-abrams": dict(born="1912-07-23", birth_place="Лонг-Бранч, Нью-Джерси, США", birth_coords=[40.304, -73.992], died="2015-04-21", death_place="Итака, Нью-Йорк, США", death_coords=[42.444, -76.5019], nationality="американец", alma_mater="Гарвардский университет", affiliations=["Корнеллский университет"], fields=["литературоведение", "романтизм"]),
 "michael-dummett": dict(born="1925-06-27", birth_place="Лондон", birth_coords=LON, died="2011-12-27", death_place="Оксфорд, Англия", death_coords=OXF, nationality="британец", alma_mater="Крайст-Чёрч, Оксфорд", affiliations=["Колледж Всех Душ, Оксфорд", "Нью-колледж, Оксфорд"], fields=["философия языка", "философия математики", "логика"], colleagues=L("crispin-wright")),
 "nataniel-gotorn": dict(born="1804-07-04", birth_place="Сейлем, Массачусетс, США", birth_coords=[42.5195, -70.8967], died="1864-05-19", death_place="Плимут, Нью-Гэмпшир, США", death_coords=[43.7570, -71.6881], nationality="американец", alma_mater="Боудин-колледж", fields=["проза"]),
 "nils-abel": dict(born="1802-08-05", birth_place="Недстранн, Норвегия", birth_coords=[59.35, 5.85], died="1829-04-06", death_place="Фроланд, Норвегия", death_coords=[58.53, 8.65], nationality="норвежец", alma_mater="Университет Кристиании", fields=["алгебра", "математический анализ"]),
 "ogyusten-koshi": dict(born="1789-08-21", birth_place="Париж", birth_coords=PAR, died="1857-05-23", death_place="Со, Франция", death_coords=[48.7766, 2.2908], nationality="француз", alma_mater="Политехническая школа; Школа мостов и дорог", affiliations=["Политехническая школа", "Коллеж де Франс", "Парижский университет"], fields=["математический анализ", "механика сплошных сред"]),
 "oliver-heaviside": dict(born="1850-05-18", birth_place="Кэмден-Таун, Лондон", birth_coords=[51.539, -0.1426], died="1925-02-03", death_place="Торки, Девон, Англия", death_coords=[50.4619, -3.5253], nationality="британец", alma_mater="самоучка", fields=["электротехника", "операционное исчисление", "электродинамика"], awards=["Медаль Фарадея (1922, первый лауреат)"]),
 "otto-neurath": dict(born="1882-12-10", birth_place="Вена, Австро-Венгрия", birth_coords=VIE, died="1945-12-22", death_place="Оксфорд, Англия", death_coords=OXF, nationality="австриец", alma_mater="Берлинский университет", affiliations=["Венский кружок", "Музей общества и экономики, Вена", "Институт ISOTYPE"], fields=["философия науки", "социология", "политэкономия", "визуальная статистика"], sep="https://plato.stanford.edu/entries/neurath/"),
 "p-j-nahin": dict(born="1940-11-26", nationality="американец", alma_mater="Стэнфордский университет; Калифорнийский технологический институт; Калифорнийский университет в Ирвайне", affiliations=["Университет Нью-Гэмпшира"], fields=["электротехника", "история науки", "популяризация математики"]),
 "paul-hindemith": dict(born="1895-11-16", birth_place="Ханау, Германия", birth_coords=[50.1264, 8.9283], died="1963-12-28", death_place="Франкфурт-на-Майне, Германия", death_coords=[50.1109, 8.6821], nationality="немец", alma_mater="Консерватория Хоха, Франкфурт", affiliations=["Берлинская высшая школа музыки", "Йельский университет"], fields=["композиция", "теория музыки"]),
 "pierre-duhem": dict(born="1861-06-09", birth_place="Париж", birth_coords=PAR, died="1916-09-14", death_place="Кабреспин, Франция", death_coords=[43.37, 2.45], nationality="француз", alma_mater="Высшая нормальная школа", affiliations=["Лилльский университет", "Реннский университет", "Университет Бордо"], fields=["термодинамика", "философия науки", "история науки"], sep="https://plato.stanford.edu/entries/duhem/"),
 "r-southey": dict(born="1774-08-12", birth_place="Бристоль, Англия", birth_coords=[51.4545, -2.5879], died="1843-03-21", death_place="Кесуик, Камберленд, Англия", death_coords=[54.6013, -3.1347], nationality="британец", alma_mater="Баллиол-колледж, Оксфорд", fields=["поэзия", "историческая проза"], colleagues=L("coleridge", "william-wordsworth"), awards=["Поэт-лауреат Великобритании (1813)"]),
 "ray-jackendoff": dict(born="1945", nationality="американец", alma_mater="Суортмор-колледж; Массачусетский технологический институт", affiliations=["Брандейский университет", "Университет Тафтса"], fields=["лингвистика", "семантика", "когнитивная наука", "музыкальное познание"]),
 "rene-descartes": dict(born="1596-03-31", birth_place="Лаэ (ныне Декарт), Турень, Франция", birth_coords=[46.97, 0.70], died="1650-02-11", death_place="Стокгольм, Швеция", death_coords=[59.3293, 18.0686], nationality="француз", alma_mater="Коллегия Ла Флеш; Университет Пуатье", fields=["метафизика", "эпистемология", "математика", "натурфилософия"], sep="https://plato.stanford.edu/entries/descartes/"),
 "richard-vagner": dict(born="1813-05-22", birth_place="Лейпциг, Саксония", birth_coords=[51.3397, 12.3731], died="1883-02-13", death_place="Венеция, Италия", death_coords=[45.4408, 12.3155], nationality="немец", alma_mater="Лейпцигский университет", fields=["композиция", "оперная драматургия"]),
 "roaring-lion": dict(born="1908", died="1999", nationality="тринидадец", fields=["калипсо"]),
 "robert-boyle": dict(born="1627-01-25", birth_place="Лисмор, Уотерфорд, Ирландия", birth_coords=[52.1367, -7.9309], died="1691-12-31", death_place="Лондон", death_coords=LON, nationality="англо-ирландец", alma_mater="Итонский колледж", affiliations=["Оксфорд", "Королевское общество"], fields=["химия", "натурфилософия", "механистическая философия"], colleagues=L("isaac-newton"), sep="https://plato.stanford.edu/entries/boyle/"),
 "robert-brandom": dict(born="1950", nationality="американец", alma_mater="Йельский университет; Принстонский университет", affiliations=["Питтсбургский университет"], fields=["философия языка", "инференциализм", "прагматизм"], teachers=L("david-lewis"), colleagues=L("wilfrid-sellars")),
 "robert-fludd": dict(born="1574", birth_place="Берстед, Кент, Англия", birth_coords=[51.276, 0.578], died="1637-09-08", death_place="Лондон", death_coords=LON, nationality="англичанин", alma_mater="Сент-Джонс-колледж, Оксфорд", fields=["медицина", "герметизм", "космология", "теория музыки"]),
 "robert-ingersoll": dict(born="1833-08-11", birth_place="Дрезден, Нью-Йорк, США", birth_coords=[42.684, -76.957], died="1899-07-21", death_place="Доббс-Ферри, Нью-Йорк, США", death_coords=[41.0145, -73.8726], nationality="американец", fields=["ораторское искусство", "агностицизм", "право"]),
 "t-h-huxley": dict(born="1825-05-04", birth_place="Илинг, Лондон", birth_coords=[51.513, -0.3089], died="1895-06-29", death_place="Истборн, Англия", death_coords=[50.768, 0.2905], nationality="британец", alma_mater="Медицинская школа больницы Чаринг-Кросс", affiliations=["Королевская горная школа, Лондон"], fields=["сравнительная анатомия", "эволюционная биология"], colleagues=L("charles-darwin"), awards=["Медаль Копли (1888)"]),
 "thomas-browne": dict(born="1605-10-19", birth_place="Лондон", birth_coords=LON, died="1682-10-19", death_place="Норидж, Англия", death_coords=[52.6309, 1.2974], nationality="англичанин", alma_mater="Пемброк-колледж, Оксфорд; университеты Монпелье, Падуи, Лейдена", fields=["медицина", "эссеистика", "натурфилософия"]),
 "thomas-reid": dict(born="1710-04-26", birth_place="Стракан, Кинкардиншир, Шотландия", birth_coords=[57.02, -2.52], died="1796-10-07", death_place="Глазго, Шотландия", death_coords=[55.8642, -4.2518], nationality="шотландец", alma_mater="Маришал-колледж, Абердин", affiliations=["Кингз-колледж, Абердин", "Университет Глазго"], fields=["философия здравого смысла", "философия восприятия"], sep="https://plato.stanford.edu/entries/reid/"),
 "tim-erikson": dict(nationality="американец", fields=["народная музыка", "скрипка"]),
 "timothy-cooley": dict(nationality="американец", affiliations=["Калифорнийский университет в Санта-Барбаре"], fields=["этномузыкология"]),
 "uilyam-okkam": dict(born="ок. 1287", birth_place="Оккам, Суррей, Англия", birth_coords=[51.30, -0.45], died="1347-04-10", death_place="Мюнхен", death_coords=[48.1351, 11.5820], nationality="англичанин", alma_mater="Оксфордский университет", affiliations=["Орден францисканцев"], fields=["логика", "номинализм", "богословие"], sep="https://plato.stanford.edu/entries/ockham/"),
 "vasco-ronchi": dict(born="1897-12-19", birth_place="Флоренция", birth_coords=[43.7696, 11.2558], died="1988-10-31", death_place="Флоренция", death_coords=[43.7696, 11.2558], nationality="итальянец", alma_mater="Высшая нормальная школа, Пиза", affiliations=["Национальный институт оптики, Флоренция"], fields=["оптика", "история оптики"]),
 "volker-scherliess": dict(nationality="немец", fields=["музыковедение"]),
 "w-a-sorge": dict(born="1703-03-21", birth_place="Мелленбах, Шварцбург", birth_coords=[50.6, 11.1], died="1778-04-04", death_place="Лобенштайн", death_coords=[50.45, 11.64], nationality="немец", fields=["органная музыка", "теория музыки", "акустика"]),
 "wilfrid-sellars": dict(born="1912-05-20", birth_place="Анн-Арбор, Мичиган, США", birth_coords=[42.2808, -83.7430], died="1989-07-02", death_place="Питтсбург, США", death_coords=[40.4406, -79.9959], nationality="американец", alma_mater="Мичиганский университет; Ориел-колледж, Оксфорд", affiliations=["Миннесотский университет", "Йельский университет", "Питтсбургский университет"], fields=["эпистемология", "философия сознания", "философия языка"], colleagues=L("robert-brandom"), sep="https://plato.stanford.edu/entries/sellars/"),
 "willard-quine": dict(born="1908-06-25", birth_place="Акрон, Огайо, США", birth_coords=[41.0814, -81.5190], died="2000-12-25", death_place="Бостон, США", death_coords=[42.3601, -71.0589], nationality="американец", alma_mater="Оберлин-колледж; Гарвардский университет", affiliations=["Гарвардский университет"], fields=["логика", "философия языка", "эпистемология"], teachers=L("alfred-north-whitehead"), students=L("david-lewis"), colleagues=L("hilary-putnam"), sep="https://plato.stanford.edu/entries/quine/"),
 "william-hazlitt": dict(born="1778-04-10", birth_place="Мейдстон, Кент, Англия", birth_coords=[51.2704, 0.5227], died="1830-09-18", death_place="Сохо, Лондон", death_coords=[51.5136, -0.1365], nationality="англичанин", alma_mater="Новый колледж в Хакни", fields=["эссеистика", "литературная критика", "живопись"], colleagues=L("charles-lamb", "coleridge", "william-wordsworth")),
 "william-james": dict(born="1842-01-11", birth_place="Нью-Йорк, США", birth_coords=NYC, died="1910-08-26", death_place="Чокоруа, Нью-Гэмпшир, США", death_coords=[43.88, -71.23], nationality="американец", alma_mater="Гарвардская медицинская школа", affiliations=["Гарвардский университет"], fields=["психология", "прагматизм"], sep="https://plato.stanford.edu/entries/james/"),
 "william-wordsworth": dict(born="1770-04-07", birth_place="Кокермут, Камберленд, Англия", birth_coords=[54.6630, -3.3620], died="1850-04-23", death_place="Райдал-Маунт, Эмблсайд, Англия", death_coords=[54.45, -2.98], nationality="англичанин", alma_mater="Сент-Джонс-колледж, Кембридж", fields=["поэзия"], colleagues=L("coleridge", "r-southey", "charles-lamb"), awards=["Поэт-лауреат Великобритании (1843)"]),
 "wolfgang-amadeus-mozart": dict(born="1756-01-27", birth_place="Зальцбург", birth_coords=[47.8095, 13.0550], died="1791-12-05", death_place="Вена", death_coords=VIE, nationality="австриец (Зальцбургское архиепископство)", fields=["композиция"]),
 "wolfgang-hildesheimer": dict(born="1916-12-09", birth_place="Гамбург", birth_coords=[53.5511, 9.9937], died="1991-08-21", death_place="Поскьяво, Швейцария", death_coords=[46.3245, 10.0573], nationality="немец", fields=["проза", "драматургия", "биография"]),
}
ORDER = ["born", "birth_place", "birth_coords", "died", "death_place", "death_coords", "nationality", "alma_mater", "affiliations", "fields", "teachers", "students", "colleagues", "awards", "sep", "wiki_ru", "notes"]

def yval(v):
    import json
    if isinstance(v, list):
        return "[" + ", ".join(json.dumps(x, ensure_ascii=False) for x in v) + "]"
    return json.dumps(v, ensure_ascii=False)

if __name__ == "__main__":
    import glob, os, re
    os.chdir(os.path.join(os.path.dirname(__file__), "..", "content", "03-people"))
    missing = []
    for f in sorted(glob.glob("*.md")):
        pid = f[:-3]
        s = open(f, encoding="utf8").read()
        end = s.index("\n---\n", 4)
        fm, rest = s[:end], s[end:]
        have = set(re.findall(r"^([a-z_]+):", fm, re.M))
        data = BIO.get(pid, {})
        if not data: missing.append(pid)
        add = [f"{k}: {yval(data[k])}" for k in ORDER if k in data and k not in have]
        if "bio_checked" not in have: add.append("bio_checked: false")
        if not add: continue
        # вставить после years:, иначе после type:/status:
        m = re.search(r"^years:.*$", fm, re.M) or re.search(r"^status:.*$", fm, re.M) or re.search(r"^type:.*$", fm, re.M)
        fm = fm[:m.end()] + "\n" + "\n".join(add) + fm[m.end():]
        open(f, "w", encoding="utf8").write(fm + rest)
    print("без данных:", missing)


# Причина смерти (добавлено 09.10.2026): только хорошо задокументированные случаи; спорное помечено.
CAUSE = {
    "bertrand-russell": "грипп", "buster-keaton": "рак лёгких", "cary-grant": "инсульт",
    "charles-darwin": "болезнь сердца", "charles-lamb": "рожистое воспаление после падения",
    "coleridge": "сердечная недостаточность", "david-hume": "рак (предположительно, кишечника или печени)",
    "david-lewis": "осложнения сахарного диабета", "doctor-seuss": "рак ротовой полости",
    "dzherri-fodor": "болезнь Паркинсона, последствия инсульта", "george-berkeley": "внезапная смерть (предположительно, инсульт)",
    "heinrich-hertz": "гранулематоз с полиангиитом (предположительно)", "helen-keller": "последствия инсультов",
    "hermann-helmholtz": "кровоизлияние в мозг", "hilaire-belloc": "ожоги и шок после падения в камин",
    "hilary-putnam": "мезотелиома", "j-l-austin": "рак лёгких", "john-dewey": "пневмония",
    "l-susan-stebbing": "рак", "leonhard-euler": "кровоизлияние в мозг", "ludwig-wittgenstein": "рак простаты",
    "nils-abel": "туберкулёз", "otto-neurath": "сердечный приступ", "paul-hindemith": "острый панкреатит",
    "pierre-duhem": "сердечный приступ", "rene-descartes": "пневмония (по другой версии — отравление)",
    "richard-vagner": "сердечный приступ", "robert-ingersoll": "сердечная недостаточность",
    "t-h-huxley": "сердечный приступ", "uilyam-okkam": "предположительно, чума", "william-hazlitt": "рак желудка (предположительно)",
    "william-james": "сердечная недостаточность", "william-wordsworth": "плеврит",
    "wolfgang-amadeus-mozart": "острая лихорадочная болезнь; точная причина неизвестна",
}


def add_cause():
    import glob, json, os, re
    os.chdir(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "content", "03-people"))
    for pid, cause in CAUSE.items():
        f = pid + ".md"
        s = open(f, encoding="utf8").read()
        end = s.index("\n---\n", 4)
        fm = s[:end]
        if re.search(r"^cause_of_death:", fm, re.M):
            continue
        m = re.search(r"^death_coords:.*$", fm, re.M) or re.search(r"^death_place:.*$", fm, re.M) or re.search(r"^died:.*$", fm, re.M)
        line = "cause_of_death: " + json.dumps(cause, ensure_ascii=False)
        fm = fm[:m.end()] + "\n" + line + fm[m.end():]
        open(f, "w", encoding="utf8").write(fm + s[end:])
    print("причина смерти:", len(CAUSE))


if __name__ == "__main__":
    add_cause()
